### ISSUE TITLE
Milestones for v0.2

### ISSUE THREAD

**Issue by ekiefl** [ekiefl/pooltool#34]
- [ ] settings available in menu
- [ ] installer for mac
- [x] screen size
- [x] fix mouse locking

**Comment by ekiefl** [comment]
https://github.com/ekiefl/pooltool/commit/6692639e3ab53ab3ecb07328a181dbf992fccce2 addresses screen sizing.

- I didn't realize this, but much of what I've done on the visualization side of things _relies_ on a 1.6 : 1 aspect ratio. Ideally the aspect ratio would be a user variable, but that's not gonna happen. As a result, the aspect ratio of pooltool windows is now officially 1.6 : 1. Take it or leave it.
- Although the aspect ratio is fixed, users can adjust the the window to whatever they want, however their window size will be overwritten by a comparable window size if they do not adhere to roughly 1.6 : 1. This may seem restrictive, but it is very helpful because it is very hard to manually adjust a window size until the game doesn't look squished/stretched.
- My graphics card doesn't seem to like adjustable windows and simplepbr: https://discourse.panda3d.org/t/simplepbr-breaks-window-resize/28655 Hopefully this is a one-off for my old laptop.

Screen size can now be adjusted wh

**Comment by ekiefl** [comment]
6b7c09f0bd7d0be9b748ea3b1bddf4cd60eec1ca and c3afdf96af2c96af1cfb620f2d3a6bfe21237349 address mouse behavior so it feels good. Users should now never feel like the mouse is locked when it shouldn't be. This was done by introducing `PurgatoryMode` that is entered whenever the window becomes inactive (alt-tabbing, clicking outside the window, etc). In purgatory, the mouse is guaranteed to be free.

Incidental to this, now when the window is inactive the frame rate can be reduced dramatically, saving processing power.

**Comment by ekiefl** [comment]
Closing all self-created issues. These topics have been moved to my internal dev board.
